// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ImuSubscriber.h
 * This header file contains the declaration of the subscriber functions.
 *
 * This file was generated by the tool fastddsgen (version: 2.5.3).
 */


#ifndef _FAST_DDS_GENERATED_MY_SENSOR_MSGS_MSG_IMU_SUBSCRIBER_H_
#define _FAST_DDS_GENERATED_MY_SENSOR_MSGS_MSG_IMU_SUBSCRIBER_H_

#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/dds/subscriber/DataReaderListener.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>
#include "ImuPubSubTypes.h"
#include <mutex>
class ImuSubscriber
{
public:
    using CallbackType = std::function<void(const my_sensor_msgs::msg::Imu&)>;
    ImuSubscriber();

    virtual ~ImuSubscriber();

    bool init(std::string topic_name, int domain_id);
    void set_callback(CallbackType callback);
    void run();

private:

    eprosima::fastdds::dds::DomainParticipant* participant_;
    eprosima::fastdds::dds::Subscriber* subscriber_;
    eprosima::fastdds::dds::Topic* topic_;
    eprosima::fastdds::dds::DataReader* reader_;
    eprosima::fastdds::dds::TypeSupport type_;

    class SubListener : public eprosima::fastdds::dds::DataReaderListener
    {
    public:

        SubListener() = default;

        ~SubListener() override = default;

        void on_data_available(
                eprosima::fastdds::dds::DataReader* reader) override;

        void on_subscription_matched(
                eprosima::fastdds::dds::DataReader* reader,
                const eprosima::fastdds::dds::SubscriptionMatchedStatus& info) override;

        int matched = 0;
        uint32_t samples = 0;
        void set_callback(CallbackType callback);
    private:
        CallbackType callback_;
        std::mutex callback_mutex_;
    }
    listener_;
};

#endif // _FAST_DDS_GENERATED_MY_SENSOR_MSGS_MSG_IMU_SUBSCRIBER_H_